---
name: Deploy Contracts for QA

on:
  workflow_dispatch: # Manually triggered from GitHub Actions tab
  pull_request:
    types: [labeled] # Triggered by a label in a PR

permissions: read-all

env:
  CHAIN_ID: 31
  ENVIRONMENT: "qa"
  DEPLOYMENTS_DIR: "deployments/"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'deploy to QA'
    environment:
      name: QA
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de" # v1.4.0
        with:
          version: stable

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76" # v2.0.2

      - name: "Install the Node.js dependencies"
        run: "bun install"

      - name: "Install the jq"
        run: "sudo apt-get update && sudo apt-get install jq direnv"

      - name: "Load and export environment variables"
        id: load-env
        run: |
          cp .env.private.example .env
          echo "$CHAIN_ID" > .chain_id
          source .envrc
          echo "RPC_URL=$RPC_URL" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT" >> $GITHUB_ENV
          echo "REWARD_TOKEN_ADDRESS=$REWARD_TOKEN_ADDRESS" >> $GITHUB_ENV
          echo "GOVERNOR_ADDRESS=$GOVERNOR_ADDRESS" >> $GITHUB_ENV

          echo "KYC_APPROVER_ADDRESS=$KYC_APPROVER_ADDRESS" >> $GITHUB_ENV
          echo "NO_DD=$NO_DD" >> $GITHUB_ENV
          echo "GAS_PRICE=$GAS_PRICE" >> $GITHUB_ENV
          echo "STAKING_TOKEN_ADDRESS=$STAKING_TOKEN_ADDRESS" >> $GITHUB_ENV

          echo "CHANGE_EXECUTOR_ADDRESS=$CHANGE_EXECUTOR_ADDRESS" >> $GITHUB_ENV
          echo "STAKING_TOKEN_ADDRESS=$STAKING_TOKEN_ADDRESS" >> $GITHUB_ENV
          echo "CHANGE_EXECUTOR_ADDRESS=$CHANGE_EXECUTOR_ADDRESS" >> $GITHUB_ENV
          echo "FOUNDATION_TREASURY_ADDRESS=$FOUNDATION_TREASURY_ADDRESS" >> $GITHUB_ENV
          echo "UPGRADER_ADDRESS=$UPGRADER_ADDRESS" >> $GITHUB_ENV
          echo "REWARD_PERCENTAGE_COOLDOWN=$REWARD_PERCENTAGE_COOLDOWN" >> $GITHUB_ENV
          echo "CYCLE_DURATION=$CYCLE_DURATION" >> $GITHUB_ENV
          echo "DISTRIBUTION_DURATION=$DISTRIBUTION_DURATION" >> $GITHUB_ENV
          echo "CYCLE_START_OFFSET=$CYCLE_START_OFFSET" >> $GITHUB_ENV

          echo "PRIVATE_KEY=${{ secrets.QA_DEPLOYMENT_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo $PWD

      - name: "Deploy Contract"
        run: "bun run deploy"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: contracts
          path: deployments/testnet_qa
